### ISSUE TITLE
Dealing with NA values

### ISSUE THREAD

**Issue by srlanalytics** [srlanalytics/bdfm#27] opened 2018-12-15 02:23 UTC
Lines 31 and 32 in seas_we() are problematic as ts_box drops NA values:

```
data <- tsbox::ts_ts(data)
dates <- tsbox::ts_df(data)$time #this drops NA values
```
For example, the following won't work because the length of `dates` does not agree with the length of `data`:

```
wil5000 <- read_csv(system.file("Examples/Wil5000.csv", package = "bdfm"),
                        col_types = cols(Date = col_date(format = "%Y-%m-%d"))
)
wil5000 <- data.frame(wil5000)
y <- ts_ts(wil5000)
sa <-seas_we(y, effect = "weekdays", holiday = NULL, transformation = "log", verbose = T)
```

The fundamental problem is that R time series formats are typically very bad and handling mixed frequency data (hoary plain-vanilla tabular data!)

Any thoughts on how to get around this?

**Comment by christophsax** [comment] 2018-12-15 03:11
Side remark:

Using `reprex::reprex()` really *a lot*. For example, I would like to have run your example above, but cannot

library(readr)
wil5000 <- read_csv(system.file("Examples/Wil5000.csv", package = "bdfm"),
                        col_types = cols(Date = col_date(format = "%Y-%m-%d"))
)
wil5000 <- data.frame(wil5000)
y <- ts_ts(wil5000)
sa <-seas_we(y, effect = "weekdays", holiday = NULL, transformation = "log", verbose = T)

**Comment by christophsax** [comment] 2018-12-15 03:42
``` r
library(readr)
library(bdfm)

wil5000 <- read_csv(system.file("Examples/Wil5000.csv", package = "bdfm"),
col_types = cols(Date = col_date(format = "%Y-%m-%d"))
)
sa <- seas_we(wil5000, effect = "weekdays")
#> Loading required namespace: tsbox
#> [time]: 'Date' [value]: 'Value' 
#> [time]: 'Date' [value]: 'Value' 
#> [time]: 'Date' [value]: 'Value'

tsbox::ts_plot(wil5000, predict(sa))
#> [time]: 'Date' [value]: 'Value' 
#> [time]: 'Date' [value]: 'Value' 
#> [time]: 'Date' [value]: 'Value'
```

![](https://i.imgur.com/hQcM6pF.png)

<sup>Created on 2018-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### Side remark

Using `reprex::reprex()` helps really *a lot* when dealing with issues, because it forces you to produce a reproducible example. E.g., you have to state all your dependencies. But it also takes care of plots, as in this example above.

**Comment by srlanalytics** [comment] 2018-12-16 22:54
Sorry... didn't mean to close this.

**Comment by christophsax** [comment] 2019-01-23 10:51
This is a tsbox issue: https://github.com/christophsax/tsbox/issues/114

**Comment by christophsax** [comment] 2019-03-16 12:38
Having a POSIXct instead of Date was only part of the issue. Still exists in latest tsbox. I added more minimal example at:

https://github.com/christophsax/tsbox/issues/137

**Comment by christophsax** [comment] 2019-03-17 17:52
This is fixed in latest tsbox:

``` r
library(readr)
library(tsbox)
library(bdfm)

wil5000 <- read_csv(system.file("Examples/Wil5000.csv", package = "bdfm"),
                        col_types = cols(Date = col_date(format = "%Y-%m-%d"))
)

wil5000 <- data.frame(wil5000)
head(wil5000)
#>         Date    Value
#> 1 2013-11-21 18680.35
#> 2 2013-11-22 18766.53
#> 3 2013-11-25 18741.95
#> 4 2013-11-26 18759.68
#> 5 2013-11-27 18812.33
#> 6 2013-11-28       NA

y <- ts_ts(wil5000)
#> [time]: 'Date' [value]: 'Value'
test <- ts_data.frame(y)
head(test)
#>         time    value
#> 1 2013-11-21 18680.35
#> 2 2013-11-22 18766.53
#> 3 2013-11-23       NA
#> 4 2013-11-24       NA
#> 5 2013-11-25 18741.95
#> 6 2013-11-26 18759.68
```

<sup>Created on 2019-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Closed** 2019-06-15 09:07 UTC
Labels: bug
